application: tcgridengine
version: 3
runtime: python
api_version: 1
builtins:
- datastore_admin: on
handlers:

- url: /tick.*
  script: services.py
- url: /guestbook.*
  script: guestbook.py
- url: /forms.*
  script: protorpc/webapp/forms.py
- url: .*
  script: guestbook.py
